// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Sat May 20 23:46:27 2023

frekvencije frekvencije_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.300Hz(300Hz_sig) ,	// output  300Hz_sig
	.262Hz(262Hz_sig) ,	// output  262Hz_sig
	.294Hz(294Hz_sig) ,	// output  294Hz_sig
	.330Hz(330Hz_sig) ,	// output  330Hz_sig
	.350Hz(350Hz_sig) ,	// output  350Hz_sig
	.392Hz(392Hz_sig) ,	// output  392Hz_sig
	.440Hz(440Hz_sig) ,	// output  440Hz_sig
	.523Hz(523Hz_sig) ,	// output  523Hz_sig
	.493Hz(493Hz_sig) 	// output  493Hz_sig
);

